### ISSUE TITLE
Discussion : gwt-material-addins 

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material#172]
Hi to all, 

We are planning on 1.5 to separate all the custom components built in gwt-material from Materializecss core components. GWT Bootstrap Team have the same idea , they made <a href="https://github.com/gwtbootstrap3/gwtbootstrap3-extras">gwt-bootstrap-extras</a> repository to indicate their custom build components.

Here are the lists of custom components :
- Time Picker
- Subheader
- Autocomplete
- Window Modal
- Steppers
- CutOut
- Side Profile

We just want to hear from you if its good idea to separate it.

You can find the repo <a href="https://github.com/GwtMaterialDesign/gwt-material-addins">here</a> 

Best Regards,
Mark

**Comment by gilberto-torrezan** [comment]
It makes sense to separate to be able to respond quickly when a new version of Materializecss is released - gwt-material-addins and gwt-material don't have to share the same package version number.

From the user standpoint, importing two projects instead of one is not a big deal (that would happen if a new version of  gwt-material is released and the gwt-material-addins is not updated to import the new version).

From the contributor standpoint, some explanation about where to put some classes would be needed. For example: utilitary classes, pure GWT implementation of core components and so on.

A question: let's suppose Materializecss releases a component which is currently implemented at the gwt-material-addins project. What would happen to the component? Would it be ported?

**Comment by kevzlou7979** [comment]
@gilberto-torrezan Yes its the idea, all users who want to contribute will easily pull there request here on gwt-material-addins to separate it from the core components.

We will provide all the information where the user can put their classes (I think it will be the same like gwt-material-addins' package structure : e.g the base, helper, mixins, ui etc.).

Answer to your question: 
<b>Scenario</b>
That's a very good question, e.g If Materializecss releases Autocomplete then we have it also on gwt-material-addins 
<b>Solution</b>
What we will do is we don't need to delete the existing component then let the user choose whether he/she wants to use the Materializecss Autocomplete component or gwt-material-addins Autocomplete.

**Comment by remarkNS** [comment]
+1

**Comment by kevzlou7979** [comment]
The repositor now is available at https://github.com/GwtMaterialDesign/gwt-material-addins
