### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by andjimrio** [GwtMaterialDesign/gwt-material#18]
We want to thank all your work, from the entire team onLibrary. We are a small group of students who are making an application in GWT, from Seville, Spain. At first we was very ugly, but when you find your JAR, all sorted!

Also, if you want, you can see how we stayed and give us feedback to improve (ol-onlibrary.appspot.com).

I would also like to give you some suggestions:
1. I can download the new version of your JAR, but the "GettingStart" button does not work in your web.
2. You could teach how to use the API from Java classes, which is how we have done.
3. You could add tables Materialize.

Thank you very much.

**Comment by kevzlou7979** [comment]
Hi,

Thanks for the wonderful message about your Library and our contribution.
As we are now developing some software also for this GWT MAterial DEsign.
We will push this thru with our best.

For your suggestions we are developing it now. Last few weeks we have a
urgent Internal Project in our company that's why we didint have updates on
sites.

Best Regards,
Kevin

On Thu, May 21, 2015 at 1:18 AM, Andrés M. Jiménez <notifications@github.com

**Comment by kevzlou7979** [comment]
Hi,

We just developed the Starter Template, this template structure will start you to modify some UI/UX in your library. 

Regards,
Kevin
