### ISSUE TITLE
MaterialButton's textColor is not applying the actual label element but on the outer button container element

### ISSUE THREAD

**Issue by kyr0** [GwtMaterialDesign/gwt-material#269]
When putting a textColor attribute on a MaterialButton, the CSS class gets applied on the < button > element, but the text of the button is rendered in a < span > element of the < button >.

Example:
< MaterialButton textColor="textColorClassName" text="fooBar" / >

Results in:
< button class="textColorClassName" > 
    < i some icon / >
    < span >
        fooBar
    < / span >
< / button >

So the class selector has to look like:

.textColorClassName > span {
    color: ...;
}

For my understanding it's better to have it like:

< button > 
    < i some icon / >
    < span class="textColorClassName" >
        fooBar
    < / span >
< / button >

The CSS selector then would look like:

.textColorClassName {
    color: ...;
}

...which seems much better to me :)

Best,
Aron

**Comment by kyr0** [comment]
Another thing: textColor attribute adds "-text" to the end of the class name. I find that a bit irritating. For what is it good?

See: ensureTextColorFormat() in ColorsMixin

**Comment by kyr0** [comment]
And next is: The iconColor attribute applies the class name on the right element but also adds "-text". So for example: iconColor="black" becomes:

< button >
    < i class="black-text" / >
...

**Comment by gilberto-torrezan** [comment]
About the `-text` class on text colors: that's intended. Materializecss defines the color classes for texts and for backgrounds in different classes, so there's not much we can do about it if we want to reuse their CSS. More about it on the [project website](http://materializecss.com/color.html).

**Comment by kyr0** [comment]
@gilberto-torrezan Ah okay, so putting "blue" would, if the class would be applied to the < span > automatically match the materializecss "blue-text" -- this makes sense, thank you for the explaination :)

Btw: What is the best way to support this project? I could fork it, push some improvements and pull u some the patches for the things I discover. You could then decide if you would like to merge?

**Comment by kyr0** [comment]
Code to reproduce:

    < m:MaterialButton 
        iconColor="blue" 
        backgroundColor="blue" 
        textColor="blue" 
        text="Add" 
        iconType="ADD" 
        iconPosition="LEFT" 
        waves="LIGHT" / >

Generated DOM:

    < button type="button" class="btn waves-effect waves-light blue blue-text" style="cursor: pointer;">
        < i class="material-icons left blue-text" style="cursor: pointer;" >add< / i >
        < span >Add< / span >
     < / button >

**Comment by gilberto-torrezan** [comment]
Hey kyr0, yes, use the standard way of making pull requests on a git project. Create a fork, then create a branch (you don't have to, but I recommend it), make the contribution you want, push it to your fork, and then on GitHub create a pull request to a branch on this project. Deciding which branch sometimes is tricky, but as a rule of thumb, use this: does your contribution breaks compatibility with previous version? Then create a pull request to the release_1.X branch. Is it a bug fix? Create a PR to the master.

@BenDol is quite sensitive to tabs instead of spaces on the code (seriously, he will track where you live, invade your home, and smash your face on the screen till you repeat 1024 times that you'll use spaces and never tabs), so make sure you read the [contribution guide](https://github.com/GwtMaterialDesign/gwt-material/wiki/Contributing) before making a pull request.

Every PR is evaluated by the project team before the final merge. Sometimes it may take a while but it always happens.

You can use the [gitter](https://gitter.im/GwtMaterialDesign/gwt-material) chat as well to talk about stuff related to the project in a more "instant messaging" way if you like.

**Comment by kevzlou7979** [comment]
@gilberto-torrezan Thanks for explaining the Contribution Guide, @kyr0 All logic behind the coloring is intended and required on materializecss.

**Comment by kyr0** [comment]
@gilberto-torrezan Thank you for the introduction! :) I will do so! :)

@kevzlou7979 Okay, I understand that the coloring is intended and in sync with the materializecss guidelines. But, the class is still applied on the < button > element instead of the < span > element, where the text is rendered into. 

Instead of:

< button type="button" class="btn waves-effect waves-light blue blue-text" style="cursor: pointer;">
    < i class="material-icons left blue-text" style="cursor: pointer;" >add< / i >
    < span >Add< / span >
 < / button >

I think it should be:

< button type="button" class="btn waves-effect waves-light blue" style="cursor: pointer;">
    < i class="material-icons left blue-text" style="cursor: pointer;" >add< / i >
    < span class="blue-text" >Add< / span >
 < / button >

So that the blue-text class applies it's "color" style to the actual text.
Currently it applies to the elements < i > and < span > and they are not inheriting it.

:)

Best,
Aron
