### ISSUE TITLE
A isOpen() method for Window

### ISSUE THREAD

**Issue by kyr0** [GwtMaterialDesign/gwt-material#270]
It would be nice if the Window class would have an isOpen() method to check if a window instance currently is open or not. My current solution is to extend the Window base class like this:

```
public class Window extends MaterialWindow {

    private boolean open = false;

    public boolean isOpen() {
        return this.open;
    }

    public void openWindow() {
        super.openWindow();
        open = true;
    }

    public void closeWindow() {
        super.closeWindow();
        open = false;
    }
}
```

**Comment by kevzlou7979** [comment]
Ok will create the method :)

**Comment by kevzlou7979** [comment]
Also next time, please post all issue related to addins <a href="https://github.com/GwtMaterialDesign/gwt-material-addins/issues"> here </a>. So that we can determine easily. 

I have fixed now the issue https://github.com/GwtMaterialDesign/gwt-material-addins/commit/53e6066f0987f3af6e5968f855df45ae8ac62512
