### ISSUE TITLE
MaterialListBox PlaceHolder text not displayed correctly 

### ISSUE THREAD

**Issue by wkok** [GwtMaterialDesign/gwt-material#358]
MaterialListBox PlaceHolderText not displayed correctly. Seems that the placeholder text for all MaterialListBox items are squashed together on top of the view / on the navigation bar:

`
MaterialListBox categoryListBox = new MaterialListBox();
categoryListBox.setPlaceholder("Category");
`

<img width="402" alt="screen shot 2016-06-07 at 12 11 14 pm" src="https://cloud.githubusercontent.com/assets/5214136/15854312/84fc8e78-2ca9-11e6-8289-e332bc73ce65.png">

**Comment by kevzlou7979** [comment]
I found the problem, It was on MaterialListValueBox base class regression, the super.onLoad() is not called that's why the setInitialClass("input-field") is not applied. So I solved it by adding it. Also another problem is on the MaterialListBox constructor it does not call the super constructor of MaterialListValueBox so its another regression. Thanks for catching up. 

Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/1b3f813564ac2f44fcd902680f27fa60055db183

Note: Make sure you set the grid option of your listbox as other input fields does to have the label / placeholder display well.

```xml
<m:MaterialListBox grid="s12" placeholder="My Placeholder">
    ...... options here
</m:MaterialListBox>
```
