### ISSUE TITLE
2.0 - Showcase New Look and Feel

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material#417]
Hi,

As of 2.0 release, we want to upgrade the look and feel of the showcase documentation.
If you have any great idea / design patter we will accept it and review.
Just submit the links of the website we want to follow the pattern.

Thanks

**Comment by gilberto-torrezan** [comment]
Since this project is intended to bring the material design to GWT applications, the first thought about the design of the showcase is to follow the material design page: https://material.google.com/

In terms of documentation organization, I like the bootstrap page: http://getbootstrap.com/components - it's nothing fancy, but it puts everything you need to know in front of you, plain and simple.

**Comment by dvallejo00** [comment]
Other example is http://gwtbootstrap3.github.io/gwtbootstrap3-demo/#home

**Comment by kevzlou7979** [comment]
@gilberto-torrezan Yeah probably let's just have the Google Material Design as primary look and feel.
@dvallejo00 Thanks for the suggestion.

I have take a look http://www.material-ui.com/ this one take a look how they document each component. They have a good documentation which I like it. Especially the display of code (at first the code is not visible until they click the CODE icon then display it. Also the API attributes is a good UX, I like also how they provide a table lists of API documentation which helps the user to see what are the available Attributes, Events etc. on each component.
