### ISSUE TITLE
Edit have program model ?

### ISSUE THREAD

**Issue by Neo110** [GwtMaterialDesign/gwt-material#512]
Edit have program model ?    
 
Syntax highlighting

**Comment by remarkNS** [comment]
This is so strange, I am not English native speaker but I thought I can understand most of it. I have to say that I am completely puzzled with this question. Anyway, I think it's much better to ask questions on gitter chat rooms (https://gitter.im/GwtMaterialDesign/gwt-material) than opening the issue here.
