### ISSUE TITLE
Date Picker problem on Mozilla Firefox (re-open with more infos)

### ISSUE THREAD

**Issue by reofake** [GwtMaterialDesign/gwt-material#558]
Original : [issue](https://github.com/GwtMaterialDesign/gwt-material/issues/556).

This issue is visible on your website, and only on Mozilla Firefox (no problem on IE11, Chrome, Edge).

To reproduce :
1- Open that link : http://gwtmaterialdesign.github.io/gwt-material-demo/#pickers
2- Click on the first datePicker (back of the page is set in backgroung, maybe the problem ?)
3- Close it by clicking outside
4- Scroll a bit up and down
5- Click the last datePicker
=> the picker is not at the place that you think it is (it is visually well placed , but it's not possible to click on the buttons)

**Comment by kevzlou7979** [comment]
I see whats going on here, the issue was the container of the datepicker was set to body instead of the datepicker itself, that's why it scrolls down everytime you open a datepicker. The solution I've got is the ability to set the container of the datepicker. 

```java
datepicker.setContainer(DatePickerContainer.BODY); // will set to the body, good fit for modals.
datepicker.setContainer(DatePickerContainer.SELF); // will set to itself to avoid scrolling down.

```
Fixed via https://github.com/GwtMaterialDesign/gwt-material/commit/f91142d8eef7450c4e460d6b9ae389a7698fe134

**Comment by reofake** [comment]
Tested OK for me.

**Comment by kevzlou7979** [comment]
@reofake Cool
