### ISSUE TITLE
MaterialButton lacks interfaces

### ISSUE THREAD

**Issue by anton-johansson** [GwtMaterialDesign/gwt-material#58]
Hi!

The MaterialButton lacks interfaces that the GWT standard Button has, for example:
 * HasEnabled
 * HasDoubleClickHandlers
 * HasFocus
 * HasAllFocusHandlers
 * etc

When developing Material Design components, we should try to keep existing GWT functionality, otherwise most of the components are useless. This goes for all components that does not extend their original class, but instead extend Composite or MaterialWidget, for example MaterialTextArea.

**Comment by John-Kellner** [comment]
Thank you !

The most of the components are useless when they are not extends the standard functionality for every single gwt widget. I currently try out GwtMaterialDesign. It makes easy to build up a responsitive website. But it's hard to bring in business logic because of missing handler like setSelected handler, click handler and a lot of more...
