### ISSUE TITLE
Z-index

### ISSUE THREAD

**Issue by LeshaRB** [GwtMaterialDesign/gwt-material#606]
And why do you use so often "z-index"

Here are a couple of places where I noticed this:
```
.top-panel {
...
    z-index: 5;
}

.waves-effect {
...
    z-index: 1;
}

nav .button-collapse {
...
    z-index: 1;
}

```

It just forces me to override the standard gwt styles
In my application, for example, PopupDialogPresenter

.gwt-PopupPanelGlass {
    background-color: #000;
    opacity: .3;
    filter: alpha(opacity=30);
}

So I need add here z-index

**Comment by kevzlou7979** [comment]
Hi @LeshaRB , It's from Materialize documentation. If we don't use z-index it will not behave well, maybe it's time for you to learn basic z-indexing because it helps you to stack element on each other.

https://www.w3schools.com/cssref/pr_pos_z-index.asp

I created an api for any MaterialWidget to set their z-index, make use of it. ```setDepth(index)```

**Comment by kevzlou7979** [comment]
Try to remove the z-index if it is useless to you, and see that it will cause you a lot of error because ```absolute``` and ```fixed``` positioned elements require it to stack those elements in an ordered manner. Please study it before posting this as an issue.
