### ISSUE TITLE
Funding suggestion

### ISSUE THREAD

**Issue by remarkNS** [GwtMaterialDesign/gwt-material#63]
I think you should try to embed ads like http://materializecss.com are doing. Not like the last time you did with popping advertisements that ruins all the demo but discreet ones like they did.

**Comment by kevzlou7979** [comment]
We tried to book a campaign on Carbon Ads, but we didnt receive any feedback from them. Also what we know is the CArbon Ads is an invite only ads.

**Comment by remarkNS** [comment]
Hmmm, than  I guess you need to attract more people with the project to be more "hot" as they say on Carbon. Google groups I think you did once, have you tried Google+ GWT ~ 3000 members: https://plus.google.com/u/0/communities/116543000751323604177 , LinkedIn GWT Users ~ 6000 members: https://www.linkedin.com/grp/home?gid=129889, LinkedIn GWT Developers ~ 4000 members: https://www.linkedin.com/grp/home?gid=1803845 , other sites that talks about GWT, web, design, technology, ... ?

**Comment by Kusig** [comment]
Donation projects always have problems, even Wikipedia .. Only big projects with most of the time a company with a reliable business case behind do work for  a long time reliable.
Therefore, it's simple, you need a business case.

Why don't you bind the donation to a specific benefit. Examples:

a) One has a bug but doesn't have the time or the skills to fix it himself. So he could donate eg. 20$ and get's for this a priority fix within a defined time frame.

b) One has a specific feature requrest. With a donation of eg. 50$ he will get this within a defined time frame.

Of course the height of the needed donation to get a bugfix or feature prioritised must be negotiatable before, eg. in an issue where you estimate the needed efforts first.

This way the project (you and others involved actively) get funded for your efforts and the crowd could spend work or money. At the end it is again a profit for all because all flows back in the project anyhow.

**Comment by kevzlou7979** [comment]
Thanks @Kusig for the proposal. We will review this altogether next year about the funding proposal.

**Comment by silentsnooc** [comment]
Should I ever be able to make money using this library you can count on my donations for sure!

**Comment by vegegoku** [comment]
I going to donate if ever this project raise a funding compaign.
