### ISSUE TITLE
MaterialSearch: open(), close() inconsistent with focus CSS

### ISSUE THREAD

**Issue by esodevel** [GwtMaterialDesign/gwt-material#729]
The `MaterialSearch` methods `open()` and `close()` handle style differently then the CSS for the focused and unfocused search field. This can lead to inconsistent rendering of the search field icons after the state is modified programmatically. The  problem is that `MaterialSearch.setActive(boolean)` sets explicit colors for the icons of which the color style names remain set even when the focused state changes and therefore different CSS styles are applied. As the colors are already applied by the focus styles and `open()/close()` fire focus events setting all color settings could be removed from `setActive()`. I tried that in a subclass and then the rendering is as it should be.

Addition: if the input field changes focus the active state is not set. This can cause inconsistencies with `open()/close()` if these are invoked according to the state returned by `isActive()`. Therefore `MaterialSearch` should problably have internal focus and blur handlers that set the active state.

Further addition: `setActive()` should also invoke `setVisible()` on the close icon or else it will still be clickable in unfocused style.

**Comment by kevzlou7979** [comment]
Thanks Im working now on this.

**Comment by kevzlou7979** [comment]
The setActive(boolean) was intended to do some UI Style updates on the search field. Can you show me a screenshot about the real issue you've got as I can't imagine that in my mind. Thanks in advance.

**Comment by esocode** [comment]
In my particular case I'm using the search field a bit different than usual because it is always visible in the NavBar besides some icons (in the desktop layout of my app). I also added a click handler to the search icon to allow the user to open and close the search field because all other elements are not visible in inactive state. I used so the visual inconsistencies I described occurred. When these are fixed the close icon becomes invisbile correctly (because of the transparent color in the CSS) but it is still there and therefore can be clicked. It should either be hidden or disabled in an inactive search field.
