### ISSUE TITLE
Migrate demo from kevzlou7979/GWTMaterialDesign into GwtMaterialDesign/gwt-material-demo

### ISSUE THREAD

**Issue by slugmandrew** [GwtMaterialDesign/gwt-material#75]
#### The Plan

* Remove redundant classes and tidy existing code
* Add GWTP and restructure as MVP
* Pages do not need to be widgets - replace with Presenter-View-UiB triplets
* Documentation for less-experienced maven users

**Comment by slugmandrew** [comment]
Posting screenshot of conversation between @christianlacerda and myself to fill in the others - we're about to make it less confusing guys, don't worry!

![image](https://cloud.githubusercontent.com/assets/153625/9072789/1eca08fc-3af5-11e5-86a9-afba8ee16bd6.png)

**Comment by kevzlou7979** [comment]
Hi, Thanks for the great plan. Yes we can use GWTP and mavenize the project. Just let me know when you will migrate because I have some minor changes on kevzlou7979/gwt-material-demo including the updates of Chips and Autocomplete showcase. I will let you know if I implement it on the showcase. 

About the release updates, I confirmed that 1.3.4 and 1.3.5 are minor releases plus Material Chips, Material Autocomplete and Material Time Picker. On 1.4 release will be the migration of GWTMaterialDesign demos (showcase, gwt-material-starter, wrenx ) and also the migration of Materializecss version 0.96 to 0.97 inshort 1.4 will be a migration release.

Cheers everyone,
Kevzlou797

**Comment by remarkNS** [comment]
Any progress on this ?

**Comment by BenDol** [comment]
I have just finished this for 1.4. release.

**Comment by remarkNS** [comment]
Great job Ben !
