### ISSUE TITLE
Cards - Grid example -Slow animation

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material#799]
Tested in 
Browser  : Firefox39+
OS: Windows10
Demo: https://gwtmaterialdesign.github.io/gwt-material-demo/2.1/#cards - GridExample Section

**Comment by kevzlou7979** [comment]
Fixed the issue, it was the internal calculation of missing parent's offset top that's why the delay takes more time than expected. Now it was fixed by adding the parent's offset top calculation in the animation logic.

![show_grid](https://user-images.githubusercontent.com/3138071/40593288-2cfd1cd6-625a-11e8-9f18-2377ced15e02.gif)

**Comment by marecrismatias1** [comment]
Confirmed in IE11,Safari9,Firefox39 and Android:Chrome
