### ISSUE TITLE
Collapsible - Calling Set Active does not close the previous item.

### ISSUE THREAD

**Issue by marecrismatias1** [GwtMaterialDesign/gwt-material#800]
When opening the Third collapsible item, then calling set active to the First Item we will expect that third item must be closed but on the demo its not closing.

![image](https://user-images.githubusercontent.com/39285900/40093139-5e761472-58f3-11e8-88e2-7f6e769ffea9.png)

Browser: Firefox39+
OS: Windows10
Demo: https://gwtmaterialdesign.github.io/gwt-material-demo/2.1/#collapsible - Accordion Section

**Comment by kevzlou7979** [comment]
In accordion type - fixed the setting active on each collapsible item 
Expected behaviour:
- Only single item must be only active

![image](https://user-images.githubusercontent.com/3138071/40521370-d5139bf2-5ffd-11e8-8fda-c09997f05f56.png)

Added demo also on expandable type
Expected behaviour:
- Can do multiple active actives because it's expandable.

![image](https://user-images.githubusercontent.com/3138071/40521413-14142d76-5ffe-11e8-8dea-5c989c126a6a.png)

**Comment by kevzlou7979** [comment]
Ready for retest @marecrismatias1

**Comment by kevzlou7979** [comment]
Ready for retest @marecrismatias1
