### ISSUE TITLE
DataTable causes page to not load when used in MVP

### ISSUE THREAD

**Issue by lcrmj** [GwtMaterialDesign/gwt-material#895]
Using DataTable in a MVP place causes
```javascript
PlaceManagerImpl.java:284 Uncaught Error: com.google.web.bindery.event.shared.UmbrellaException: Exception caught: (TypeError) : $wnd.$ is not a function
```

I've placed a demo on https://github.com/lcrmj/gmd-datatable-issue-demo using the archetype as base

**Comment by kevzlou7979** [comment]
Are you using GWTP?

**Comment by lcrmj** [comment]
Yes

**Comment by kevzlou7979** [comment]
Ok got it reproduced will be fixing this on 2.2-SNAPSHOT

**Comment by kevzlou7979** [comment]
Off note Will be creating a new demo showcase to easily determine if any changes from previous released had issues.

**Comment by kevzlou7979** [comment]
We found out the issue on the $wnd is undefined, we browse our Errai project and found out that GWTP loading mechanism is different from it. So the problem was the JQuery is not loaded before the GWTP module loaded. So I browse our demo showcase (NEW) and move the <inherits name="com.gwtplatform.mvp.MvpWithEntryPoint"/> <extend-configuration-property name="gin.ginjector.modules" value="gmd.core.demo.client.gin.ClientModule"/> below the gwt-material module inheritance
 <module rename-to='GmdCoreDemo'>
    <inherits name='com.google.gwt.user.User'/>

    
    <source path='client'/>
    <source path='shared'/>

    
    <inherits name="gwt.material.design.GwtMaterialBasicWithJQuery"/>
    <inherits name="gwt.material.design.incubator.AddinsIncubator"/>
    <inherits name="gwt.material.design.incubator.FontAwesomeResources"/>
    <inherits name="gwt.material.design.themes.ThemeBlue"/>

    
    <inherits name="com.gwtplatform.mvp.MvpWithEntryPoint"/>
    <extend-configuration-property name="gin.ginjector.modules" value="gmd.core.demo.client.gin.ClientModule"/>

    <inherits name="com.google.gwt.precompress.Precompress"/>

    <set-configuration-property name="CssResource.enableGss" value="true"/>

    
    <collapse-all-properties value="true" />

</module>
_

**Comment by kevzlou7979** [comment]
Also dont forget to include your datatable module import
