### ISSUE TITLE
Material SideNav : Clip (Permanent)

### ISSUE THREAD

**Issue by kevzlou7979** [GwtMaterialDesign/gwt-material#92]
Implement type="clip" in Material SideNav Component

<h4>Clip (Permanent)</h4>
Navigation drawer clipped under the app bar: Apps focused on productivity that require balance across the screen

![image](https://cloud.githubusercontent.com/assets/3138071/10043368/72590f58-61a7-11e5-884c-bca1b555c2a3.png)

**Comment by kevzlou7979** [comment]
<h3>Result</h3>

<h4>For Desktop </h4>
![image](https://cloud.githubusercontent.com/assets/3138071/10043407/ad5f3cbc-61a7-11e5-9d73-90a5bc176c58.png)

<h4>For Mobile </h4>
![clip-sidenav](https://cloud.githubusercontent.com/assets/3138071/10043424/e89f7dd2-61a7-11e5-8805-0bd14159f749.gif)

**Comment by leforthomas** [comment]
Has this feature been removed? There is no such type "CLIP" anymore.

**Comment by kevzlou7979** [comment]
Yeah we removed it for consistency of sidenav types.
Don't worry we just have a sidenav properties to reach the CLIP design.
http://gwtmaterialdesign.github.io/gwt-material-demo/#!sidenavs
Under FIXED Variation #2

Watch also this one:
https://www.youtube.com/watch?v=e-XY4EGVIuc
On 8:20 minutes

**Comment by leforthomas** [comment]
May be I misunderstand the terminology.
I would like the main panel to be pushed when the fixed sidenav is deployed. Currently if I set the sidenav to FIXED, it covers the content of the main panel. See image attached. This is from the demo code and all I did is changed to FIXED and top to 64px. I would like the main content to be moved. I could use the push type but the push also pushes the header. All I need is FIXED with the ability to move the content when shown. I have a workaround with css but I would rather it'd be the default behaviour.

![fixedsidenav](https://cloud.githubusercontent.com/assets/1318091/18162130/40c88408-7035-11e6-89ff-bca3cf00a609.png)
